import Footer from '@components/Footer'
import Nav from '@components/Nav'
import { Nunito, Poppins } from 'next/font/google'
import Head from 'next/head'
import React from 'react'

const poppin = Poppins({
	weight: '400',
	subsets: ['latin'],
})

const nunito = Nunito({
	subsets: ['latin'],
	weight: '500',
})
interface LayoutProps {
	title: string
	children: React.ReactElement
}
const Layout = ({ title, children }: LayoutProps) => {
	return (
		<div>
			<Head>
				<title>{title}</title>
				<meta name='description' content='Generated by Zeeshan Mustfai' />
				<meta name='viewport' content='width=device-width, initial-scale=1' />
				<link rel='icon' href='/favicon.ico' />
			</Head>
			<div className={nunito.className}>
				<Nav />
				<main>{children}</main>
				<Footer />
			</div>
		</div>
	)
}

export default Layout
