import Head from 'next/head'
import { Poppins } from 'next/font/google'
import Footer from '@components/Footer'
import Nav from '@components/Nav'
import BlogPreview from '@components/BlogPreview'
import { Container, Grid } from '@nextui-org/react'
import { list } from '../mock/blogList'
import { getAllPosts } from '../lib/blog-api'
import { HomeProps } from '../types'

const poppin = Poppins({
	weight: '400',
	subsets: ['latin'],
})

export const getStaticProps = async () => {
	const postList = await getAllPosts()
	return {
		props: {
			posts: postList,
		},
	}
}

export default function Home({ posts }: HomeProps) {
	console.log('posts', posts)
	return (
		<>
			<Head>
				<title>My Blog</title>
				<meta name='description' content='Generated by create next app' />
				<meta name='viewport' content='width=device-width, initial-scale=1' />
				<link rel='icon' href='/favicon.ico' />
			</Head>
			<main className={poppin.className}>
				<Nav />
				<Container md>
					<Grid.Container gap={2}>
						{posts.map((item) => {
							return (
								<Grid key={item.slug} xs={12} sm={6} md={4}>
									<BlogPreview blogData={item.data} />
								</Grid>
							)
						})}
					</Grid.Container>
				</Container>

				{/* <Footer /> */}
			</main>
		</>
	)
}
