import Head from 'next/head'
import { Poppins } from 'next/font/google'
import Footer from '@components/Footer/Footer'
const poppin = Poppins({
	weight: '400',
	subsets: ['latin'],
})

export default function Home() {
	return (
		<>
			<Head>
				<title>My Blog</title>
				<meta name='description' content='Generated by create next app' />
				<meta name='viewport' content='width=device-width, initial-scale=1' />
				<link rel='icon' href='/favicon.ico' />
			</Head>
			<main className={poppin.className}>
				<p className={'title'}>Hello world</p>
				<Footer />
			</main>
		</>
	)
}
